name: release

on:
  push: 
    paths: BuildTrigger.txt
  milestone: 
    types: [ created , edited , closed ]
  workflow_dispatch: 
env:
  BUILD_VERSION: "1.19.1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo chmod 777 ${{github.workspace}}/build.sh
          sudo bash -c ${{github.workspace}}/build.sh

      - name: Upload Artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{github.workspace}}/spigot.jar
          asset_name: spigot-${{env.BUILD_VERSION}}.jar
          tag: "main"
          overwrite: true
          release_name: "Prebuilt Spigot server executable"
          body: "Prebuilt Spigot server executable"