name: release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: ${{github.workspace}}\build.bat

      - name: Upload Artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{github.workspace}}\spigot-1.19.2.jar
          # repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: spigot-1.19.2.jar
          tag: "main"
          overwrite: true
          release_name: "Prebuilt Spigot server executable"
          body: "Prebuilt Spigot server executable"