name: release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: ${{github.workspace}}\build.bat

      # - name: Create Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: "main"
      #     release_name: "Prebuilt Spigot server executable for 1.20.4"
      #     body: "Prebuilt Spigot server executable for 1.20.4"
      #     draft: false
      #     prerelease: false
      # - name: Upload Artifact to release
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
      #     asset_path: ${{github.workspace}}\spigot-1.20.4.jar
      #     asset_name: spigot-1.20.4.jar
      #     asset_content_type: application/java-archive



      - name: Upload Artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{github.workspace}}\spigot-1.20.4.jar
          # repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: spigot-1.20.4.jar
          tag: "main"
          overwrite: true
          release_name: "Prebuilt Spigot server executable"
          body: "Prebuilt Spigot server executable"
      - name: Upload Artifact to action
        uses: actions/upload-artifact@v1
        with: 
          name: spigot-1.20.4
          path: ${{github.workspace}}\spigot-1.20.4.jar